// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { CreateAssistantResponseOthers } from "./CreateAssistantResponseOthers.js";

export const CreateAssistantResponse: core.serialization.ObjectSchema<
    serializers.CreateAssistantResponse.Raw,
    FlaqzApp.CreateAssistantResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: CreateAssistantResponseOthers,
});

export declare namespace CreateAssistantResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: CreateAssistantResponseOthers.Raw;
    }
}
