// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetAssistantsResponseOthers } from "./GetAssistantsResponseOthers.js";

export const GetAssistantsResponse: core.serialization.ObjectSchema<
    serializers.GetAssistantsResponse.Raw,
    FlaqzApp.GetAssistantsResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: GetAssistantsResponseOthers,
});

export declare namespace GetAssistantsResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: GetAssistantsResponseOthers.Raw;
    }
}
