// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetAssistantsResponseOthersData } from "./GetAssistantsResponseOthersData.js";

export const GetAssistantsResponseOthers: core.serialization.ObjectSchema<
    serializers.GetAssistantsResponseOthers.Raw,
    FlaqzApp.GetAssistantsResponseOthers
> = core.serialization.object({
    data: GetAssistantsResponseOthersData.optional(),
});

export declare namespace GetAssistantsResponseOthers {
    export interface Raw {
        data?: GetAssistantsResponseOthersData.Raw | null;
    }
}
