// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Assistant } from "../../../types/Assistant.js";

export const GetAssistantsResponseOthersData: core.serialization.ObjectSchema<
    serializers.GetAssistantsResponseOthersData.Raw,
    FlaqzApp.GetAssistantsResponseOthersData
> = core.serialization.object({
    data: core.serialization.list(Assistant),
    total: core.serialization.string(),
});

export declare namespace GetAssistantsResponseOthersData {
    export interface Raw {
        data: Assistant.Raw[];
        total: string;
    }
}
