// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Campaign } from "../../../types/Campaign.js";

export const SearchCampaignsResponseOthersData: core.serialization.ObjectSchema<
    serializers.SearchCampaignsResponseOthersData.Raw,
    FlaqzApp.SearchCampaignsResponseOthersData
> = core.serialization.object({
    data: core.serialization.list(Campaign),
    total: core.serialization.number(),
});

export declare namespace SearchCampaignsResponseOthersData {
    export interface Raw {
        data: Campaign.Raw[];
        total: number;
    }
}
