// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SearchCampaignsResponseOthersData } from "./SearchCampaignsResponseOthersData.js";

export const SearchCampaignsResponseOthers: core.serialization.ObjectSchema<
    serializers.SearchCampaignsResponseOthers.Raw,
    FlaqzApp.SearchCampaignsResponseOthers
> = core.serialization.object({
    data: SearchCampaignsResponseOthersData.optional(),
});

export declare namespace SearchCampaignsResponseOthers {
    export interface Raw {
        data?: SearchCampaignsResponseOthersData.Raw | null;
    }
}
