// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SearchCampaignsResponseOthers } from "./SearchCampaignsResponseOthers.js";

export const SearchCampaignsResponse: core.serialization.ObjectSchema<
    serializers.SearchCampaignsResponse.Raw,
    FlaqzApp.SearchCampaignsResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: SearchCampaignsResponseOthers,
});

export declare namespace SearchCampaignsResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: SearchCampaignsResponseOthers.Raw;
    }
}
