// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SearchAssistantsResponseOthers } from "./SearchAssistantsResponseOthers.js";

export const SearchAssistantsResponse: core.serialization.ObjectSchema<
    serializers.SearchAssistantsResponse.Raw,
    FlaqzApp.SearchAssistantsResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: SearchAssistantsResponseOthers,
});

export declare namespace SearchAssistantsResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: SearchAssistantsResponseOthers.Raw;
    }
}
