// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Assistant } from "../../../types/Assistant.js";

export const UpdateAssistantResponseOthers: core.serialization.ObjectSchema<
    serializers.UpdateAssistantResponseOthers.Raw,
    FlaqzApp.UpdateAssistantResponseOthers
> = core.serialization.object({
    data: Assistant.optional(),
});

export declare namespace UpdateAssistantResponseOthers {
    export interface Raw {
        data?: Assistant.Raw | null;
    }
}
