// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { CreateCampaignResponseOthers } from "./CreateCampaignResponseOthers.js";

export const CreateCampaignResponse: core.serialization.ObjectSchema<
    serializers.CreateCampaignResponse.Raw,
    FlaqzApp.CreateCampaignResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: CreateCampaignResponseOthers,
});

export declare namespace CreateCampaignResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: CreateCampaignResponseOthers.Raw;
    }
}
