// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { DeleteCampaignResponseOthers } from "./DeleteCampaignResponseOthers.js";

export const DeleteCampaignResponse: core.serialization.ObjectSchema<
    serializers.DeleteCampaignResponse.Raw,
    FlaqzApp.DeleteCampaignResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: DeleteCampaignResponseOthers,
});

export declare namespace DeleteCampaignResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: DeleteCampaignResponseOthers.Raw;
    }
}
