// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const DeleteCampaignResponseOthers: core.serialization.ObjectSchema<
    serializers.DeleteCampaignResponseOthers.Raw,
    FlaqzApp.DeleteCampaignResponseOthers
> = core.serialization.object({
    data: core.serialization.string().optional(),
});

export declare namespace DeleteCampaignResponseOthers {
    export interface Raw {
        data?: string | null;
    }
}
