// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { PublishCampaignResponseOthers } from "./PublishCampaignResponseOthers.js";

export const PublishCampaignResponse: core.serialization.ObjectSchema<
    serializers.PublishCampaignResponse.Raw,
    FlaqzApp.PublishCampaignResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: PublishCampaignResponseOthers,
});

export declare namespace PublishCampaignResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: PublishCampaignResponseOthers.Raw;
    }
}
