// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Campaign } from "../../../types/Campaign.js";

export const PublishCampaignResponseOthers: core.serialization.ObjectSchema<
    serializers.PublishCampaignResponseOthers.Raw,
    FlaqzApp.PublishCampaignResponseOthers
> = core.serialization.object({
    data: Campaign.optional(),
});

export declare namespace PublishCampaignResponseOthers {
    export interface Raw {
        data?: Campaign.Raw | null;
    }
}
