// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const RunCampaignResponseOthersData: core.serialization.ObjectSchema<
    serializers.RunCampaignResponseOthersData.Raw,
    FlaqzApp.RunCampaignResponseOthersData
> = core.serialization.object({
    vapiCampaignId: core.serialization.string(),
});

export declare namespace RunCampaignResponseOthersData {
    export interface Raw {
        vapiCampaignId: string;
    }
}
