// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { RunCampaignResponseOthers } from "./RunCampaignResponseOthers.js";

export const RunCampaignResponse: core.serialization.ObjectSchema<
    serializers.RunCampaignResponse.Raw,
    FlaqzApp.RunCampaignResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: RunCampaignResponseOthers,
});

export declare namespace RunCampaignResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: RunCampaignResponseOthers.Raw;
    }
}
