// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { UpdateCampaignResponseOthers } from "./UpdateCampaignResponseOthers.js";

export const UpdateCampaignResponse: core.serialization.ObjectSchema<
    serializers.UpdateCampaignResponse.Raw,
    FlaqzApp.UpdateCampaignResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: UpdateCampaignResponseOthers,
});

export declare namespace UpdateCampaignResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: UpdateCampaignResponseOthers.Raw;
    }
}
