// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { LoginResponseOthers } from "./LoginResponseOthers.js";

export const LoginResponse: core.serialization.ObjectSchema<serializers.LoginResponse.Raw, FlaqzApp.LoginResponse> =
    core.serialization.object({
        status: core.serialization.number(),
        success: core.serialization.boolean(),
        message: core.serialization.string(),
        others: LoginResponseOthers,
    });

export declare namespace LoginResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: LoginResponseOthers.Raw;
    }
}
