// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { AuthTokens } from "../../../types/AuthTokens.js";

export const LoginResponseOthers: core.serialization.ObjectSchema<
    serializers.LoginResponseOthers.Raw,
    FlaqzApp.LoginResponseOthers
> = core.serialization.object({
    data: AuthTokens.optional(),
});

export declare namespace LoginResponseOthers {
    export interface Raw {
        data?: AuthTokens.Raw | null;
    }
}
