// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { RefreshResponseOthers } from "./RefreshResponseOthers.js";

export const RefreshResponse: core.serialization.ObjectSchema<
    serializers.RefreshResponse.Raw,
    FlaqzApp.RefreshResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: RefreshResponseOthers,
});

export declare namespace RefreshResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: RefreshResponseOthers.Raw;
    }
}
