// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         provider: "11labs",
 *         model: "eleven_flash_v2",
 *         voiceId: "33B4UnXyTNbgLmdEDh5P",
 *         autoMode: true,
 *         speed: 1,
 *         style: 0,
 *         stability: 0.5,
 *         similarity: 0.5,
 *         optimize: 2
 *     }
 */
export interface CreateVoiceInput {
    provider: string | null;
    model: string | null;
    voiceId: string | null;
    autoMode: boolean | null;
    speed: number | null;
    style: number | null;
    stability: number | null;
    similarity: number | null;
    optimize: number | null;
}
