// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             provider: "11labs",
 *             model: "eleven_flash_v2",
 *             voiceId: "33B4UnXyTNbgLmdEDh5P",
 *             autoMode: true,
 *             speed: 1,
 *             style: 0,
 *             stability: 0.5,
 *             similarity: 0.5,
 *             optimize: 2
 *         }
 *     }
 */
export interface UpdateVoiceRequest {
    id: string;
    body: FlaqzApp.CreateVoiceInput;
}
