// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import type * as FlaqzApp from "../../../index.js";

export declare namespace VoiceClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class VoiceClient {
    protected readonly _options: VoiceClient.Options;

    constructor(options: VoiceClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {FlaqzApp.GetVoicesRequest} request
     * @param {VoiceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.voice.getVoices({
     *         page: 1,
     *         pageSize: 20
     *     })
     */
    public getVoices(
        request: FlaqzApp.GetVoicesRequest,
        requestOptions?: VoiceClient.RequestOptions,
    ): core.HttpResponsePromise<FlaqzApp.GetVoicesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getVoices(request, requestOptions));
    }

    private async __getVoices(
        request: FlaqzApp.GetVoicesRequest,
        requestOptions?: VoiceClient.RequestOptions,
    ): Promise<core.WithRawResponse<FlaqzApp.GetVoicesResponse>> {
        const { page, pageSize } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.page = page.toString();
        _queryParams.pageSize = pageSize.toString();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FlaqzAppEnvironment.Default,
                "api/v1/voices",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.GetVoicesResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FlaqzAppError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FlaqzAppError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FlaqzAppTimeoutError("Timeout exceeded when calling GET /api/v1/voices.");
            case "unknown":
                throw new errors.FlaqzAppError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {FlaqzApp.CreateVoiceInput} request
     * @param {VoiceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.voice.createVoice({
     *         provider: "11labs",
     *         model: "eleven_flash_v2",
     *         voiceId: "33B4UnXyTNbgLmdEDh5P",
     *         autoMode: true,
     *         speed: 1,
     *         style: 0,
     *         stability: 0.5,
     *         similarity: 0.5,
     *         optimize: 2
     *     })
     */
    public createVoice(
        request: FlaqzApp.CreateVoiceInput,
        requestOptions?: VoiceClient.RequestOptions,
    ): core.HttpResponsePromise<FlaqzApp.CreateVoiceResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createVoice(request, requestOptions));
    }

    private async __createVoice(
        request: FlaqzApp.CreateVoiceInput,
        requestOptions?: VoiceClient.RequestOptions,
    ): Promise<core.WithRawResponse<FlaqzApp.CreateVoiceResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FlaqzAppEnvironment.Default,
                "api/v1/voices",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: serializers.CreateVoiceInput.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CreateVoiceResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FlaqzAppError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FlaqzAppError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FlaqzAppTimeoutError("Timeout exceeded when calling POST /api/v1/voices.");
            case "unknown":
                throw new errors.FlaqzAppError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {FlaqzApp.SearchVoicesRequest} request
     * @param {VoiceClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.voice.searchVoices({
     *         page: 1,
     *         pageSize: 20,
     *         query: "Awesome Customer"
     *     })
     */
    public searchVoices(
        request: FlaqzApp.SearchVoicesRequest,
        requestOptions?: VoiceClient.RequestOptions,
    ): core.HttpResponsePromise<FlaqzApp.SearchVoicesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__searchVoices(request, requestOptions));
    }

    private async __searchVoices(
        request: FlaqzApp.SearchVoicesRequest,
        requestOptions?: VoiceClient.RequestOptions,
    ): Promise<core.WithRawResponse<FlaqzApp.SearchVoicesResponse>> {
        const { page, pageSize, query } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.page = page.toString();
        _queryParams.pageSize = pageSize.toString();
        _queryParams.query = query;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FlaqzAppEnvironment.Default,
                "api/v1/voices/search",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.SearchVoicesResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FlaqzAppError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FlaqzAppError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FlaqzAppTimeoutError("Timeout exceeded when calling GET /api/v1/voices/search.");
            case "unknown":
                throw new errors.FlaqzAppError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
