// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { CreateVoiceResponseOthers } from "./CreateVoiceResponseOthers.js";

export const CreateVoiceResponse: core.serialization.ObjectSchema<
    serializers.CreateVoiceResponse.Raw,
    FlaqzApp.CreateVoiceResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: CreateVoiceResponseOthers,
});

export declare namespace CreateVoiceResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: CreateVoiceResponseOthers.Raw;
    }
}
