// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { DeleteVoiceResponseOthers } from "./DeleteVoiceResponseOthers.js";

export const DeleteVoiceResponse: core.serialization.ObjectSchema<
    serializers.DeleteVoiceResponse.Raw,
    FlaqzApp.DeleteVoiceResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: DeleteVoiceResponseOthers,
});

export declare namespace DeleteVoiceResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: DeleteVoiceResponseOthers.Raw;
    }
}
