// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { DeleteVoiceResponseOthersData } from "./DeleteVoiceResponseOthersData.js";

export const DeleteVoiceResponseOthers: core.serialization.ObjectSchema<
    serializers.DeleteVoiceResponseOthers.Raw,
    FlaqzApp.DeleteVoiceResponseOthers
> = core.serialization.object({
    data: DeleteVoiceResponseOthersData.optional(),
});

export declare namespace DeleteVoiceResponseOthers {
    export interface Raw {
        data?: DeleteVoiceResponseOthersData.Raw | null;
    }
}
