// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Voice } from "../../../types/Voice.js";

export const GetVoicesResponseOthers: core.serialization.ObjectSchema<
    serializers.GetVoicesResponseOthers.Raw,
    FlaqzApp.GetVoicesResponseOthers
> = core.serialization.object({
    data: core.serialization.list(Voice).optional(),
});

export declare namespace GetVoicesResponseOthers {
    export interface Raw {
        data?: Voice.Raw[] | null;
    }
}
