// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetVoicesResponseOthers } from "./GetVoicesResponseOthers.js";

export const GetVoicesResponse: core.serialization.ObjectSchema<
    serializers.GetVoicesResponse.Raw,
    FlaqzApp.GetVoicesResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: GetVoicesResponseOthers,
});

export declare namespace GetVoicesResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: GetVoicesResponseOthers.Raw;
    }
}
