// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetVoicesResponseOthersData } from "./GetVoicesResponseOthersData.js";

export const GetVoicesResponseOthers: core.serialization.ObjectSchema<
    serializers.GetVoicesResponseOthers.Raw,
    FlaqzApp.GetVoicesResponseOthers
> = core.serialization.object({
    data: GetVoicesResponseOthersData.optional(),
});

export declare namespace GetVoicesResponseOthers {
    export interface Raw {
        data?: GetVoicesResponseOthersData.Raw | null;
    }
}
