// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SearchVoicesResponseOthers } from "./SearchVoicesResponseOthers.js";

export const SearchVoicesResponse: core.serialization.ObjectSchema<
    serializers.SearchVoicesResponse.Raw,
    FlaqzApp.SearchVoicesResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: SearchVoicesResponseOthers,
});

export declare namespace SearchVoicesResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: SearchVoicesResponseOthers.Raw;
    }
}
