// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SearchVoicesResponseOthersData } from "./SearchVoicesResponseOthersData.js";

export const SearchVoicesResponseOthers: core.serialization.ObjectSchema<
    serializers.SearchVoicesResponseOthers.Raw,
    FlaqzApp.SearchVoicesResponseOthers
> = core.serialization.object({
    data: SearchVoicesResponseOthersData.optional(),
});

export declare namespace SearchVoicesResponseOthers {
    export interface Raw {
        data?: SearchVoicesResponseOthersData.Raw | null;
    }
}
