// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Voice } from "../../../types/Voice.js";

export const SearchVoicesResponseOthersData: core.serialization.ObjectSchema<
    serializers.SearchVoicesResponseOthersData.Raw,
    FlaqzApp.SearchVoicesResponseOthersData
> = core.serialization.object({
    data: core.serialization.list(Voice),
    total: core.serialization.number(),
});

export declare namespace SearchVoicesResponseOthersData {
    export interface Raw {
        data: Voice.Raw[];
        total: number;
    }
}
