// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SetDefaultVoiceResponseOthers } from "./SetDefaultVoiceResponseOthers.js";

export const SetDefaultVoiceResponse: core.serialization.ObjectSchema<
    serializers.SetDefaultVoiceResponse.Raw,
    FlaqzApp.SetDefaultVoiceResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: SetDefaultVoiceResponseOthers,
});

export declare namespace SetDefaultVoiceResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: SetDefaultVoiceResponseOthers.Raw;
    }
}
