// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { UpdateVoiceResponseOthers } from "./UpdateVoiceResponseOthers.js";

export const UpdateVoiceResponse: core.serialization.ObjectSchema<
    serializers.UpdateVoiceResponse.Raw,
    FlaqzApp.UpdateVoiceResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: UpdateVoiceResponseOthers,
});

export declare namespace UpdateVoiceResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: UpdateVoiceResponseOthers.Raw;
    }
}
