// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Voice } from "../../../types/Voice.js";

export const UpdateVoiceResponseOthers: core.serialization.ObjectSchema<
    serializers.UpdateVoiceResponseOthers.Raw,
    FlaqzApp.UpdateVoiceResponseOthers
> = core.serialization.object({
    data: Voice.optional(),
});

export declare namespace UpdateVoiceResponseOthers {
    export interface Raw {
        data?: Voice.Raw | null;
    }
}
