// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Transcriber } from "../../../types/Transcriber.js";

export const CreateTranscriberResponseOthers: core.serialization.ObjectSchema<
    serializers.CreateTranscriberResponseOthers.Raw,
    FlaqzApp.CreateTranscriberResponseOthers
> = core.serialization.object({
    data: Transcriber.optional(),
});

export declare namespace CreateTranscriberResponseOthers {
    export interface Raw {
        data?: Transcriber.Raw | null;
    }
}
