// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { CreateTranscriberResponseOthers } from "./CreateTranscriberResponseOthers.js";

export const CreateTranscriberResponse: core.serialization.ObjectSchema<
    serializers.CreateTranscriberResponse.Raw,
    FlaqzApp.CreateTranscriberResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: CreateTranscriberResponseOthers,
});

export declare namespace CreateTranscriberResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: CreateTranscriberResponseOthers.Raw;
    }
}
