// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { DeleteTranscriberResponseOthers } from "./DeleteTranscriberResponseOthers.js";

export const DeleteTranscriberResponse: core.serialization.ObjectSchema<
    serializers.DeleteTranscriberResponse.Raw,
    FlaqzApp.DeleteTranscriberResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: DeleteTranscriberResponseOthers,
});

export declare namespace DeleteTranscriberResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: DeleteTranscriberResponseOthers.Raw;
    }
}
