// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const DeleteTranscriberResponseOthersData: core.serialization.ObjectSchema<
    serializers.DeleteTranscriberResponseOthersData.Raw,
    FlaqzApp.DeleteTranscriberResponseOthersData
> = core.serialization.object({
    deleted: core.serialization.string(),
});

export declare namespace DeleteTranscriberResponseOthersData {
    export interface Raw {
        deleted: string;
    }
}
