// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { DeleteTranscriberResponseOthersData } from "./DeleteTranscriberResponseOthersData.js";

export const DeleteTranscriberResponseOthers: core.serialization.ObjectSchema<
    serializers.DeleteTranscriberResponseOthers.Raw,
    FlaqzApp.DeleteTranscriberResponseOthers
> = core.serialization.object({
    data: DeleteTranscriberResponseOthersData.optional(),
});

export declare namespace DeleteTranscriberResponseOthers {
    export interface Raw {
        data?: DeleteTranscriberResponseOthersData.Raw | null;
    }
}
