// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GettranscribersResponseOthersData } from "./GettranscribersResponseOthersData.js";

export const GettranscribersResponseOthers: core.serialization.ObjectSchema<
    serializers.GettranscribersResponseOthers.Raw,
    FlaqzApp.GettranscribersResponseOthers
> = core.serialization.object({
    data: GettranscribersResponseOthersData.optional(),
});

export declare namespace GettranscribersResponseOthers {
    export interface Raw {
        data?: GettranscribersResponseOthersData.Raw | null;
    }
}
