// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GettranscribersResponseOthers } from "./GettranscribersResponseOthers.js";

export const GettranscribersResponse: core.serialization.ObjectSchema<
    serializers.GettranscribersResponse.Raw,
    FlaqzApp.GettranscribersResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: GettranscribersResponseOthers,
});

export declare namespace GettranscribersResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: GettranscribersResponseOthers.Raw;
    }
}
