// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SearchTranscribersResponseOthersData } from "./SearchTranscribersResponseOthersData.js";

export const SearchTranscribersResponseOthers: core.serialization.ObjectSchema<
    serializers.SearchTranscribersResponseOthers.Raw,
    FlaqzApp.SearchTranscribersResponseOthers
> = core.serialization.object({
    data: SearchTranscribersResponseOthersData.optional(),
});

export declare namespace SearchTranscribersResponseOthers {
    export interface Raw {
        data?: SearchTranscribersResponseOthersData.Raw | null;
    }
}
