// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Transcriber } from "../../../types/Transcriber.js";

export const SearchTranscribersResponseOthersData: core.serialization.ObjectSchema<
    serializers.SearchTranscribersResponseOthersData.Raw,
    FlaqzApp.SearchTranscribersResponseOthersData
> = core.serialization.object({
    data: core.serialization.list(Transcriber),
    total: core.serialization.number(),
});

export declare namespace SearchTranscribersResponseOthersData {
    export interface Raw {
        data: Transcriber.Raw[];
        total: number;
    }
}
