// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SearchTranscribersResponseOthers } from "./SearchTranscribersResponseOthers.js";

export const SearchTranscribersResponse: core.serialization.ObjectSchema<
    serializers.SearchTranscribersResponse.Raw,
    FlaqzApp.SearchTranscribersResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: SearchTranscribersResponseOthers,
});

export declare namespace SearchTranscribersResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: SearchTranscribersResponseOthers.Raw;
    }
}
