// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SetDefaultTranscriberResponseOthers } from "./SetDefaultTranscriberResponseOthers.js";

export const SetDefaultTranscriberResponse: core.serialization.ObjectSchema<
    serializers.SetDefaultTranscriberResponse.Raw,
    FlaqzApp.SetDefaultTranscriberResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: SetDefaultTranscriberResponseOthers,
});

export declare namespace SetDefaultTranscriberResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: SetDefaultTranscriberResponseOthers.Raw;
    }
}
