// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Transcriber } from "../../../types/Transcriber.js";

export const SetDefaultTranscriberResponseOthers: core.serialization.ObjectSchema<
    serializers.SetDefaultTranscriberResponseOthers.Raw,
    FlaqzApp.SetDefaultTranscriberResponseOthers
> = core.serialization.object({
    data: Transcriber.optional(),
});

export declare namespace SetDefaultTranscriberResponseOthers {
    export interface Raw {
        data?: Transcriber.Raw | null;
    }
}
