// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Transcriber } from "../../../types/Transcriber.js";

export const UpdateTranscriberResponseOthers: core.serialization.ObjectSchema<
    serializers.UpdateTranscriberResponseOthers.Raw,
    FlaqzApp.UpdateTranscriberResponseOthers
> = core.serialization.object({
    data: Transcriber.optional(),
});

export declare namespace UpdateTranscriberResponseOthers {
    export interface Raw {
        data?: Transcriber.Raw | null;
    }
}
