// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { UpdateTranscriberResponseOthers } from "./UpdateTranscriberResponseOthers.js";

export const UpdateTranscriberResponse: core.serialization.ObjectSchema<
    serializers.UpdateTranscriberResponse.Raw,
    FlaqzApp.UpdateTranscriberResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: UpdateTranscriberResponseOthers,
});

export declare namespace UpdateTranscriberResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: UpdateTranscriberResponseOthers.Raw;
    }
}
