export * from "./assistant/client/requests/index.js";
export * as assistant from "./assistant/index.js";
export * from "./assistant/types/index.js";
export * from "./campaign/client/requests/index.js";
export * as campaign from "./campaign/index.js";
export * from "./campaign/types/index.js";
export * as campaigns from "./campaigns/index.js";
export * from "./campaigns/types/index.js";
export * from "./customer/client/requests/index.js";
export * as customer from "./customer/index.js";
export * from "./customer/types/index.js";
export * from "./model/client/requests/index.js";
export * as model from "./model/index.js";
export * from "./model/types/index.js";
export * from "./transcriber/client/requests/index.js";
export * as transcriber from "./transcriber/index.js";
export * from "./transcriber/types/index.js";
export * from "./user/client/requests/index.js";
export * as user from "./user/index.js";
export * from "./user/types/index.js";
export * from "./voice/client/requests/index.js";
export * as voice from "./voice/index.js";
export * from "./voice/types/index.js";
