// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "df727d0e-a169-4e24-8b5e-637077d57f35"
 *     }
 */
export interface RunCampaignRequest {
    id: string;
}
