// This file was auto-generated by Fern from our API Definition.

export const CreateAssistantInputFirstMsgMode = {
    SpeaksFirstWithMsg: "SPEAKS_FIRST_WITH_MSG",
    SpeaksFirst: "SPEAKS_FIRST",
    WaitForUser: "WAIT_FOR_USER",
} as const;
export type CreateAssistantInputFirstMsgMode =
    (typeof CreateAssistantInputFirstMsgMode)[keyof typeof CreateAssistantInputFirstMsgMode];
