// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../index.js";

export interface UpdateAssistantResponseOthers {
    data?: FlaqzApp.Assistant;
}
