// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import type * as FlaqzApp from "../../../index.js";

export declare namespace CustomerClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class CustomerClient {
    protected readonly _options: CustomerClient.Options;

    constructor(options: CustomerClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {FlaqzApp.GetAllCustomersRequest} request
     * @param {CustomerClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.customer.getAllCustomers({
     *         page: 1,
     *         pageSize: 20
     *     })
     */
    public getAllCustomers(
        request: FlaqzApp.GetAllCustomersRequest,
        requestOptions?: CustomerClient.RequestOptions,
    ): core.HttpResponsePromise<FlaqzApp.GetAllCustomersResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getAllCustomers(request, requestOptions));
    }

    private async __getAllCustomers(
        request: FlaqzApp.GetAllCustomersRequest,
        requestOptions?: CustomerClient.RequestOptions,
    ): Promise<core.WithRawResponse<FlaqzApp.GetAllCustomersResponse>> {
        const { page, pageSize } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.page = page.toString();
        _queryParams.pageSize = pageSize.toString();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FlaqzAppEnvironment.Default,
                "api/v1/customers",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.GetAllCustomersResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FlaqzAppError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FlaqzAppError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FlaqzAppTimeoutError("Timeout exceeded when calling GET /api/v1/customers.");
            case "unknown":
                throw new errors.FlaqzAppError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {FlaqzApp.CreateManyCustomersSchema} request
     * @param {CustomerClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.customer.createManyCustomers({
     *         customers: [{
     *                 email: "awesome@customer.com",
     *                 fullName: "Awesome Customer",
     *                 phoneNumber: "+10000000000",
     *                 ppInfo: "Under financial history analisys"
     *             }]
     *     })
     */
    public createManyCustomers(
        request: FlaqzApp.CreateManyCustomersSchema,
        requestOptions?: CustomerClient.RequestOptions,
    ): core.HttpResponsePromise<FlaqzApp.CreateManyCustomersResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createManyCustomers(request, requestOptions));
    }

    private async __createManyCustomers(
        request: FlaqzApp.CreateManyCustomersSchema,
        requestOptions?: CustomerClient.RequestOptions,
    ): Promise<core.WithRawResponse<FlaqzApp.CreateManyCustomersResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FlaqzAppEnvironment.Default,
                "api/v1/many-customers",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: serializers.CreateManyCustomersSchema.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CreateManyCustomersResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FlaqzAppError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FlaqzAppError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FlaqzAppTimeoutError("Timeout exceeded when calling POST /api/v1/many-customers.");
            case "unknown":
                throw new errors.FlaqzAppError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
