// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../index.js";

/**
 * @example
 *     {
 *         customers: [{
 *                 email: "awesome@customer.com",
 *                 fullName: "Awesome Customer",
 *                 phoneNumber: "+10000000000",
 *                 ppInfo: "Under financial history analisys"
 *             }]
 *     }
 */
export interface CreateManyCustomersSchema {
    customers: FlaqzApp.CreateCustomerInput[];
}
