// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../index.js";

/**
 * @example
 *     {
 *         customers: [{
 *                 email: "awesome@customer.com",
 *                 firstName: "Awesome",
 *                 lastName: "Customer",
 *                 phoneNumber: "+10000000000",
 *                 obs: "Mr. Awesome like oranges",
 *                 cpf: "00000000000",
 *                 birthDate: "2000-01-01",
 *                 ppInfo: "Under financial history analisys"
 *             }]
 *     }
 */
export interface CreateManyCustomersSchema {
    customers: FlaqzApp.CreateCustomerInput[];
}
