// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         page: 1,
 *         pageSize: 20
 *     }
 */
export interface GetAllCustomersRequest {
    page: number;
    pageSize: number;
}
