// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateTranscriberInput: core.serialization.Schema<
    serializers.CreateTranscriberInput.Raw,
    FlaqzApp.CreateTranscriberInput
> = core.serialization.object({
    model: core.serialization.string().nullable(),
    language: core.serialization.string().nullable(),
    provider: core.serialization.string().nullable(),
});

export declare namespace CreateTranscriberInput {
    export interface Raw {
        model?: string | null;
        language?: string | null;
        provider?: string | null;
    }
}
