// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateModelInput: core.serialization.Schema<serializers.CreateModelInput.Raw, FlaqzApp.CreateModelInput> =
    core.serialization.object({
        model: core.serialization.string().nullable(),
        provider: core.serialization.string().nullable(),
        maxTokens: core.serialization.number().nullable(),
        temperature: core.serialization.number().nullable(),
    });

export declare namespace CreateModelInput {
    export interface Raw {
        model?: string | null;
        provider?: string | null;
        maxTokens?: number | null;
        temperature?: number | null;
    }
}
