// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import type * as FlaqzApp from "../../../index.js";

export declare namespace CampaignClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class CampaignClient {
    protected readonly _options: CampaignClient.Options;

    constructor(options: CampaignClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {FlaqzApp.CreateCampaignInput} request
     * @param {CampaignClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.campaign.createCampaign({
     *         campaignName: "My Awesome Campaign",
     *         assistantId: "8df037de-a169-4e24-8b5e-637077d57f35",
     *         customerIds: ["8f727d7e-a169-4e24-8b5e-637077d57f35", "df727d0e-a169-4e27-8b5e-637077d57f35"],
     *         published: true
     *     })
     */
    public createCampaign(
        request: FlaqzApp.CreateCampaignInput,
        requestOptions?: CampaignClient.RequestOptions,
    ): core.HttpResponsePromise<FlaqzApp.CreateCampaignResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createCampaign(request, requestOptions));
    }

    private async __createCampaign(
        request: FlaqzApp.CreateCampaignInput,
        requestOptions?: CampaignClient.RequestOptions,
    ): Promise<core.WithRawResponse<FlaqzApp.CreateCampaignResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FlaqzAppEnvironment.Default,
                "api/v1/campaigns",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: serializers.CreateCampaignInput.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CreateCampaignResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FlaqzAppError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FlaqzAppError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FlaqzAppTimeoutError("Timeout exceeded when calling POST /api/v1/campaigns.");
            case "unknown":
                throw new errors.FlaqzAppError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {FlaqzApp.UpdateCampaignRequest} request
     * @param {CampaignClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.campaign.updateCampaign({
     *         id: "id",
     *         newData: {
     *             campaignName: "My Awesome Campaign",
     *             assistantId: "8df037de-a169-4e24-8b5e-637077d57f35",
     *             customerIds: ["8f727d7e-a169-4e24-8b5e-637077d57f35", "df727d0e-a169-4e27-8b5e-637077d57f35"],
     *             published: true
     *         }
     *     })
     */
    public updateCampaign(
        request: FlaqzApp.UpdateCampaignRequest,
        requestOptions?: CampaignClient.RequestOptions,
    ): core.HttpResponsePromise<FlaqzApp.UpdateCampaignResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateCampaign(request, requestOptions));
    }

    private async __updateCampaign(
        request: FlaqzApp.UpdateCampaignRequest,
        requestOptions?: CampaignClient.RequestOptions,
    ): Promise<core.WithRawResponse<FlaqzApp.UpdateCampaignResponse>> {
        const { id, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FlaqzAppEnvironment.Default,
                `api/v1/campaigns/${core.url.encodePathParam(id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: serializers.UpdateCampaignRequest.jsonOrThrow(_body, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.UpdateCampaignResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FlaqzAppError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FlaqzAppError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FlaqzAppTimeoutError("Timeout exceeded when calling PUT /api/v1/campaigns/{id}.");
            case "unknown":
                throw new errors.FlaqzAppError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {FlaqzApp.DeleteCampaignRequest} request
     * @param {CampaignClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.campaign.deleteCampaign({
     *         id: "df727d0e-a169-4e24-8b5e-637077d57f35"
     *     })
     */
    public deleteCampaign(
        request: FlaqzApp.DeleteCampaignRequest,
        requestOptions?: CampaignClient.RequestOptions,
    ): core.HttpResponsePromise<FlaqzApp.DeleteCampaignResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteCampaign(request, requestOptions));
    }

    private async __deleteCampaign(
        request: FlaqzApp.DeleteCampaignRequest,
        requestOptions?: CampaignClient.RequestOptions,
    ): Promise<core.WithRawResponse<FlaqzApp.DeleteCampaignResponse>> {
        const { id } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FlaqzAppEnvironment.Default,
                `api/v1/campaigns/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.DeleteCampaignResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FlaqzAppError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FlaqzAppError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FlaqzAppTimeoutError("Timeout exceeded when calling DELETE /api/v1/campaigns/{id}.");
            case "unknown":
                throw new errors.FlaqzAppError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {FlaqzApp.PublishCampaignRequest} request
     * @param {CampaignClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.campaign.publishCampaign({
     *         id: "id"
     *     })
     */
    public publishCampaign(
        request: FlaqzApp.PublishCampaignRequest,
        requestOptions?: CampaignClient.RequestOptions,
    ): core.HttpResponsePromise<FlaqzApp.PublishCampaignResponse> {
        return core.HttpResponsePromise.fromPromise(this.__publishCampaign(request, requestOptions));
    }

    private async __publishCampaign(
        request: FlaqzApp.PublishCampaignRequest,
        requestOptions?: CampaignClient.RequestOptions,
    ): Promise<core.WithRawResponse<FlaqzApp.PublishCampaignResponse>> {
        const { id } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FlaqzAppEnvironment.Default,
                `api/v1/campaigns/${core.url.encodePathParam(id)}/publish`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.PublishCampaignResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FlaqzAppError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FlaqzAppError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FlaqzAppTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/campaigns/{id}/publish.",
                );
            case "unknown":
                throw new errors.FlaqzAppError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
