// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         email: "user@example.com",
 *         username: "johndoe",
 *         pass: "securepassword"
 *     }
 */
export interface CreateUserInput {
    email: string;
    username: string;
    pass: string;
}
