// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { User } from "../../../types/User.js";

export const CreateUserResponseOthers: core.serialization.ObjectSchema<
    serializers.CreateUserResponseOthers.Raw,
    FlaqzApp.CreateUserResponseOthers
> = core.serialization.object({
    data: User.optional(),
});

export declare namespace CreateUserResponseOthers {
    export interface Raw {
        data?: User.Raw | null;
    }
}
