// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { CreateUserResponseOthers } from "./CreateUserResponseOthers.js";

export const CreateUserResponse: core.serialization.ObjectSchema<
    serializers.CreateUserResponse.Raw,
    FlaqzApp.CreateUserResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: CreateUserResponseOthers,
});

export declare namespace CreateUserResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: CreateUserResponseOthers.Raw;
    }
}
