// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { DeleteUserResponseOthersData } from "./DeleteUserResponseOthersData.js";

export const DeleteUserResponseOthers: core.serialization.ObjectSchema<
    serializers.DeleteUserResponseOthers.Raw,
    FlaqzApp.DeleteUserResponseOthers
> = core.serialization.object({
    data: DeleteUserResponseOthersData.optional(),
});

export declare namespace DeleteUserResponseOthers {
    export interface Raw {
        data?: DeleteUserResponseOthersData.Raw | null;
    }
}
