// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { DeleteUserResponseOthers } from "./DeleteUserResponseOthers.js";

export const DeleteUserResponse: core.serialization.ObjectSchema<
    serializers.DeleteUserResponse.Raw,
    FlaqzApp.DeleteUserResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: DeleteUserResponseOthers,
});

export declare namespace DeleteUserResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: DeleteUserResponseOthers.Raw;
    }
}
