// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetUsersResponseOthers } from "./GetUsersResponseOthers.js";

export const GetUsersResponse: core.serialization.ObjectSchema<
    serializers.GetUsersResponse.Raw,
    FlaqzApp.GetUsersResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: GetUsersResponseOthers,
});

export declare namespace GetUsersResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: GetUsersResponseOthers.Raw;
    }
}
