// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { User } from "../../../types/User.js";

export const GetUsersResponseOthers: core.serialization.ObjectSchema<
    serializers.GetUsersResponseOthers.Raw,
    FlaqzApp.GetUsersResponseOthers
> = core.serialization.object({
    data: core.serialization.list(User).optional(),
});

export declare namespace GetUsersResponseOthers {
    export interface Raw {
        data?: User.Raw[] | null;
    }
}
