// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { User } from "../../../types/User.js";

export const SearchUsersResponseOthersData: core.serialization.ObjectSchema<
    serializers.SearchUsersResponseOthersData.Raw,
    FlaqzApp.SearchUsersResponseOthersData
> = core.serialization.object({
    data: core.serialization.list(User),
    total: core.serialization.number(),
});

export declare namespace SearchUsersResponseOthersData {
    export interface Raw {
        data: User.Raw[];
        total: number;
    }
}
