// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SearchUsersResponseOthersData } from "./SearchUsersResponseOthersData.js";

export const SearchUsersResponseOthers: core.serialization.ObjectSchema<
    serializers.SearchUsersResponseOthers.Raw,
    FlaqzApp.SearchUsersResponseOthers
> = core.serialization.object({
    data: SearchUsersResponseOthersData.optional(),
});

export declare namespace SearchUsersResponseOthers {
    export interface Raw {
        data?: SearchUsersResponseOthersData.Raw | null;
    }
}
