// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SearchUsersResponseOthers } from "./SearchUsersResponseOthers.js";

export const SearchUsersResponse: core.serialization.ObjectSchema<
    serializers.SearchUsersResponse.Raw,
    FlaqzApp.SearchUsersResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: SearchUsersResponseOthers,
});

export declare namespace SearchUsersResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: SearchUsersResponseOthers.Raw;
    }
}
