// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         email: "user@example.com",
 *         pass: "securepassword"
 *     }
 */
export interface LoginInput {
    email: string;
    pass: string;
}
