// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         isGlobal: false
 *     }
 */
export interface LogoutInput {
    sessionId?: string;
    isGlobal?: boolean;
}
