// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         refreshToken: "refreshToken"
 *     }
 */
export interface RefreshInput {
    refreshToken: string;
}
