// This file was auto-generated by Fern from our API Definition.

export const AssistantStructuredOutputIdsItem = {
    SaleCompleted: "SALE_COMPLETED",
    LeadStatus: "LEAD_STATUS",
    SuccessEvalString: "SUCCESS_EVAL_STRING",
    SuccessEvalNum: "SUCCESS_EVAL_NUM",
    ProductInterestLevel: "PRODUCT_INTEREST_LEVEL",
    UpsellIdentified: "UPSELL_IDENTIFIED",
    CallSummary: "CALL_SUMMARY",
} as const;
export type AssistantStructuredOutputIdsItem =
    (typeof AssistantStructuredOutputIdsItem)[keyof typeof AssistantStructuredOutputIdsItem];
