// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../index.js";

/**
 * This is the type for assistants in our application
 */
export interface Assistant {
    id: string;
    name: string;
    /** slug is auto-generated */
    slug: string;
    voiceId: string;
    voice: FlaqzApp.Voice;
    modelId: string;
    model: FlaqzApp.Model;
    transcriberId: string;
    transcriber: FlaqzApp.Transcriber;
    prompt: string;
    firstMsg: string;
    firstMsgMode: FlaqzApp.AssistantFirstMsgMode;
    voiceMailMsg: string;
    endMsg: string;
    bgSound: FlaqzApp.AssistantBgSound;
    bgDenoising: boolean;
    structuredOutputIds: FlaqzApp.AssistantStructuredOutputIdsItem[];
    createdAt: Date;
}
