// This file was auto-generated by Fern from our API Definition.

export const AssistantBgSound = {
    Off: "OFF",
    Office: "OFFICE",
    Default: "DEFAULT",
} as const;
export type AssistantBgSound = (typeof AssistantBgSound)[keyof typeof AssistantBgSound];
