// This file was auto-generated by Fern from our API Definition.

/**
 * JWT access token and refresh token pair
 */
export interface AuthTokens {
    accessToken: string;
    refreshToken: string;
    expiresIn: number;
}
