// This file was auto-generated by Fern from our API Definition.

/**
 * This is the input type for endpoints that create or update models
 */
export interface CreateModelInput {
    model: string | null;
    provider: string | null;
    maxTokens: string | null;
    temperature: number | null;
}
