// This file was auto-generated by Fern from our API Definition.

/**
 * This is the type for inputs in routes that create a new customer
 */
export interface CreateCustomerInput {
    email: string;
    firstName: string;
    lastName: string;
    /** Must be stored in E.164 format */
    phoneNumber: string;
    /** Information about customer preferences and things like that */
    obs: string | null;
    cpf: string;
    birthDate: string | null;
    /** Must store information about customer's loan */
    ppInfo: string | null;
}
