// This file was auto-generated by Fern from our API Definition.

/**
 * This is the input type for endpoints that create or update transcribers
 */
export interface CreateTranscriberInput {
    model: string | null;
    language: string | null;
    provider: string | null;
}
