// This file was auto-generated by Fern from our API Definition.

/**
 * This is the input type for endpoints that create nor edit voices
 */
export interface CreateVoiceInput {
    provider: string | null;
    model: string | null;
    voiceId: string | null;
    autoMode: boolean | null;
    speed: number | null;
    style: number | null;
    stability: number | null;
    similarity: number | null;
    optimize: string | null;
}
