// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../index.js";

/**
 * This is the typ for campaigns in our application
 */
export interface CreateCampaignInput {
    campaignName: string;
    assistantId: string;
    customers: FlaqzApp.Customer[];
    published: boolean;
}
