// This file was auto-generated by Fern from our API Definition.

export const CreateAssistantInputBgSound = {
    Off: "OFF",
    Office: "OFFICE",
    Default: "DEFAULT",
} as const;
export type CreateAssistantInputBgSound =
    (typeof CreateAssistantInputBgSound)[keyof typeof CreateAssistantInputBgSound];
