// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../index.js";

/**
 * This is the input type for endpoints that create or update assistants
 */
export interface CreateAssistantInput {
    name: string;
    voiceId: string;
    modelId: string;
    transcriberId: string;
    prompt: string;
    firstMsg: string;
    firstMsgMode: FlaqzApp.CreateAssistantInputFirstMsgMode;
    voiceMailMsg: string;
    endMsg: string;
    bgSound: FlaqzApp.CreateAssistantInputBgSound;
    bgDenoising: boolean;
    structuredOutputIds: FlaqzApp.CreateAssistantInputStructuredOutputIdsItem[];
}
