// This file was auto-generated by Fern from our API Definition.

/**
 * This is the typ for campaigns in our application
 */
export interface CreateCampaignInput {
    campaignName: string;
    assistantId: string;
    customerIds: string[];
    published: boolean;
}
