// This file was auto-generated by Fern from our API Definition.

/**
 * This is the type for customers in our application
 */
export interface Customer {
    id: string;
    email: string;
    fullName: string;
    /** Must be stored in E.164 format */
    phoneNumber: string;
    /** Must store information about customer's loan */
    ppInfo: string | null;
    createdAt: Date;
}
