// This file was auto-generated by Fern from our API Definition.

/**
 * This is the type for models in our application
 */
export interface Model {
    id: string;
    model: string;
    provider: string;
    maxTokens: number;
    temperature: number;
    createdAt: Date;
}
