// This file was auto-generated by Fern from our API Definition.

/**
 * This is the type for transcribers in our application
 */
export interface Transcriber {
    id: string;
    model: string;
    language: string;
    provider: string;
    createdAt: Date;
}
