// This file was auto-generated by Fern from our API Definition.

/**
 * User in the application
 */
export interface User {
    id: string;
    email: string;
    username: string;
    createdAt: Date;
}
