// This file was auto-generated by Fern from our API Definition.

export const UserRole = {
    Admin: "ADMIN",
    Manager: "MANAGER",
    User: "USER",
} as const;
export type UserRole = (typeof UserRole)[keyof typeof UserRole];
