// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../index.js";

/**
 * User in the application
 */
export interface User {
    id: string;
    email: string;
    username: string;
    role: FlaqzApp.UserRole;
    createdAt: Date;
}
