// This file was auto-generated by Fern from our API Definition.

/**
 * This is the type for voices in our application
 */
export interface Voice {
    id: string;
    provider: string;
    model: string;
    voiceId: string;
    autoMode: boolean;
    speed: number;
    style: number;
    stability: number;
    similarity: number;
    optimize: number;
    createdAt: Date;
}
