// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { CreateCustomerInput } from "../../../../types/CreateCustomerInput.js";

export const CreateManyCustomersSchema: core.serialization.Schema<
    serializers.CreateManyCustomersSchema.Raw,
    FlaqzApp.CreateManyCustomersSchema
> = core.serialization.object({
    customers: core.serialization.list(CreateCustomerInput),
});

export declare namespace CreateManyCustomersSchema {
    export interface Raw {
        customers: CreateCustomerInput.Raw[];
    }
}
