// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateUserInput: core.serialization.Schema<serializers.CreateUserInput.Raw, FlaqzApp.CreateUserInput> =
    core.serialization.object({
        email: core.serialization.string(),
        username: core.serialization.string(),
        pass: core.serialization.string(),
    });

export declare namespace CreateUserInput {
    export interface Raw {
        email: string;
        username: string;
        pass: string;
    }
}
