// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         page: 1,
 *         pageSize: 20,
 *         query: "Wow a amazing campaign"
 *     }
 */
export interface SearchCampaignsRequest {
    page: number;
    pageSize: number;
    query: string;
}
