// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         newData: {
 *             name: "My Assistant 01",
 *             voiceId: "5d9f0c21-2c4a-4b4d-8b8b-aad2de5542f3",
 *             modelId: "a4ac4276-9c26-4bb0-a563-a290f2b4c91f",
 *             transcriberId: "66fa9d6b-c6ac-4baf-ade4-37e16478e4b2",
 *             prompt: "You're a assistant that call to people and ask if they know how to make a carrot cake",
 *             firstMsg: "Hello!",
 *             firstMsgMode: "SPEAKS_FIRST",
 *             voiceMailMsg: "Who uses voicemail in 2077 man",
 *             endMsg: "Bye!",
 *             bgSound: "OFFICE",
 *             bgDenoising: true,
 *             structuredOutputIds: ["SALE_COMPLETED", "LEAD_STATUS"]
 *         }
 *     }
 */
export interface UpdateAssistantRequest {
    id: string;
    newData: FlaqzApp.CreateAssistantInput;
}
