// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import type * as FlaqzApp from "../../../index.js";

export declare namespace VapiClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class VapiClient {
    protected readonly _options: VapiClient.Options;

    constructor(options: VapiClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {FlaqzApp.SearchAssistantsRequest} request
     * @param {VapiClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.vapi.searchAssistants({
     *         page: 1,
     *         pageSize: 20,
     *         query: "Awesome Customer"
     *     })
     */
    public searchAssistants(
        request: FlaqzApp.SearchAssistantsRequest,
        requestOptions?: VapiClient.RequestOptions,
    ): core.HttpResponsePromise<FlaqzApp.SearchAssistantsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__searchAssistants(request, requestOptions));
    }

    private async __searchAssistants(
        request: FlaqzApp.SearchAssistantsRequest,
        requestOptions?: VapiClient.RequestOptions,
    ): Promise<core.WithRawResponse<FlaqzApp.SearchAssistantsResponse>> {
        const { page, pageSize, query } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.page = page.toString();
        _queryParams.pageSize = pageSize.toString();
        _queryParams.query = query;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FlaqzAppEnvironment.Default,
                "api/v1/assistants/search",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.SearchAssistantsResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FlaqzAppError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FlaqzAppError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FlaqzAppTimeoutError("Timeout exceeded when calling GET /api/v1/assistants/search.");
            case "unknown":
                throw new errors.FlaqzAppError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
