// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         model: "nova-2",
 *         language: "pt-BR",
 *         provider: "deepgram"
 *     }
 */
export interface CreateTranscriberInput {
    model: string | null;
    language: string | null;
    provider: string | null;
}
