// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             model: "nova-2",
 *             language: "pt-BR",
 *             provider: "deepgram"
 *         }
 *     }
 */
export interface UpdateTranscriberRequest {
    id: string;
    body: FlaqzApp.CreateTranscriberInput;
}
