// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { CreateAssistantInput } from "../../../../types/CreateAssistantInput.js";

export const UpdateAssistantRequest: core.serialization.Schema<
    serializers.UpdateAssistantRequest.Raw,
    Omit<FlaqzApp.UpdateAssistantRequest, "id">
> = core.serialization.object({
    newData: CreateAssistantInput,
});

export declare namespace UpdateAssistantRequest {
    export interface Raw {
        newData: CreateAssistantInput.Raw;
    }
}
