// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { CreateAssistantInput } from "../../../../types/CreateAssistantInput.js";

export const UpdateAssistant: core.serialization.Schema<
    serializers.UpdateAssistant.Raw,
    Omit<FlaqzApp.UpdateAssistant, "id">
> = core.serialization.object({
    newData: CreateAssistantInput,
});

export declare namespace UpdateAssistant {
    export interface Raw {
        newData: CreateAssistantInput.Raw;
    }
}
