// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import type * as FlaqzApp from "../../../index.js";

export declare namespace AssistantClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AssistantClient {
    protected readonly _options: AssistantClient.Options;

    constructor(options: AssistantClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {FlaqzApp.GetAssistantsRequest} request
     * @param {AssistantClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.assistant.getAssistants()
     */
    public getAssistants(
        request: FlaqzApp.GetAssistantsRequest = {},
        requestOptions?: AssistantClient.RequestOptions,
    ): core.HttpResponsePromise<FlaqzApp.GetAssistantsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getAssistants(request, requestOptions));
    }

    private async __getAssistants(
        request: FlaqzApp.GetAssistantsRequest = {},
        requestOptions?: AssistantClient.RequestOptions,
    ): Promise<core.WithRawResponse<FlaqzApp.GetAssistantsResponse>> {
        const { page, pageSize } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (page !== undefined) {
            _queryParams.page = page?.toString() ?? null;
        }

        if (pageSize !== undefined) {
            _queryParams.pageSize = pageSize?.toString() ?? null;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FlaqzAppEnvironment.Default,
                "api/v1/assistants",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.GetAssistantsResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FlaqzAppError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FlaqzAppError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FlaqzAppTimeoutError("Timeout exceeded when calling GET /api/v1/assistants.");
            case "unknown":
                throw new errors.FlaqzAppError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {FlaqzApp.CreateAssistantInput} request
     * @param {AssistantClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.assistant.createAssistant({
     *         name: "My Assistant 01",
     *         voiceId: "5d9f0c21-2c4a-4b4d-8b8b-aad2de5542f3",
     *         modelId: "a4ac4276-9c26-4bb0-a563-a290f2b4c91f",
     *         transcriberId: "66fa9d6b-c6ac-4baf-ade4-37e16478e4b2",
     *         prompt: "You're a assistant that call to people and ask if they know how to make a carrot cake",
     *         firstMsg: "Hello!",
     *         firstMsgMode: "SPEAKS_FIRST",
     *         voiceMailMsg: "Who uses voicemail in 2077 man",
     *         endMsg: "Bye!",
     *         bgSound: "OFFICE",
     *         bgDenoising: true,
     *         structuredOutputIds: ["SALE_COMPLETED", "LEAD_STATUS"]
     *     })
     */
    public createAssistant(
        request: FlaqzApp.CreateAssistantInput,
        requestOptions?: AssistantClient.RequestOptions,
    ): core.HttpResponsePromise<FlaqzApp.CreateAssistantResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createAssistant(request, requestOptions));
    }

    private async __createAssistant(
        request: FlaqzApp.CreateAssistantInput,
        requestOptions?: AssistantClient.RequestOptions,
    ): Promise<core.WithRawResponse<FlaqzApp.CreateAssistantResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.FlaqzAppEnvironment.Default,
                "api/v1/assistants",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: serializers.CreateAssistantInput.jsonOrThrow(request, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CreateAssistantResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.FlaqzAppError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.FlaqzAppError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.FlaqzAppTimeoutError("Timeout exceeded when calling POST /api/v1/assistants.");
            case "unknown":
                throw new errors.FlaqzAppError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }
}
