// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { CreateModelResponseOthers } from "./CreateModelResponseOthers.js";

export const CreateModelResponse: core.serialization.ObjectSchema<
    serializers.CreateModelResponse.Raw,
    FlaqzApp.CreateModelResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: CreateModelResponseOthers,
});

export declare namespace CreateModelResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: CreateModelResponseOthers.Raw;
    }
}
