// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Model } from "../../../types/Model.js";

export const CreateModelResponseOthers: core.serialization.ObjectSchema<
    serializers.CreateModelResponseOthers.Raw,
    FlaqzApp.CreateModelResponseOthers
> = core.serialization.object({
    data: Model.optional(),
});

export declare namespace CreateModelResponseOthers {
    export interface Raw {
        data?: Model.Raw | null;
    }
}
