// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Model } from "../../../types/Model.js";

export const CreateModelResponseOthersData: core.serialization.ObjectSchema<
    serializers.CreateModelResponseOthersData.Raw,
    FlaqzApp.CreateModelResponseOthersData
> = core.serialization.object({
    data: core.serialization.list(Model),
    total: core.serialization.number(),
});

export declare namespace CreateModelResponseOthersData {
    export interface Raw {
        data: Model.Raw[];
        total: number;
    }
}
