// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { DeleteModelResponseOthers } from "./DeleteModelResponseOthers.js";

export const DeleteModelResponse: core.serialization.ObjectSchema<
    serializers.DeleteModelResponse.Raw,
    FlaqzApp.DeleteModelResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: DeleteModelResponseOthers,
});

export declare namespace DeleteModelResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: DeleteModelResponseOthers.Raw;
    }
}
