// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { DeleteModelResponseOthersData } from "./DeleteModelResponseOthersData.js";

export const DeleteModelResponseOthers: core.serialization.ObjectSchema<
    serializers.DeleteModelResponseOthers.Raw,
    FlaqzApp.DeleteModelResponseOthers
> = core.serialization.object({
    data: DeleteModelResponseOthersData.optional(),
});

export declare namespace DeleteModelResponseOthers {
    export interface Raw {
        data?: DeleteModelResponseOthersData.Raw | null;
    }
}
