// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Model } from "../../../types/Model.js";

export const GetModelsResponseOthers: core.serialization.ObjectSchema<
    serializers.GetModelsResponseOthers.Raw,
    FlaqzApp.GetModelsResponseOthers
> = core.serialization.object({
    data: core.serialization.list(Model).optional(),
});

export declare namespace GetModelsResponseOthers {
    export interface Raw {
        data?: Model.Raw[] | null;
    }
}
