// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetModelsResponseOthers } from "./GetModelsResponseOthers.js";

export const GetModelsResponse: core.serialization.ObjectSchema<
    serializers.GetModelsResponse.Raw,
    FlaqzApp.GetModelsResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: GetModelsResponseOthers,
});

export declare namespace GetModelsResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: GetModelsResponseOthers.Raw;
    }
}
