// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SearchModelsResponseOthers } from "./SearchModelsResponseOthers.js";

export const SearchModelsResponse: core.serialization.ObjectSchema<
    serializers.SearchModelsResponse.Raw,
    FlaqzApp.SearchModelsResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: SearchModelsResponseOthers,
});

export declare namespace SearchModelsResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: SearchModelsResponseOthers.Raw;
    }
}
