// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SearchModelsResponseOthersData } from "./SearchModelsResponseOthersData.js";

export const SearchModelsResponseOthers: core.serialization.ObjectSchema<
    serializers.SearchModelsResponseOthers.Raw,
    FlaqzApp.SearchModelsResponseOthers
> = core.serialization.object({
    data: SearchModelsResponseOthersData.optional(),
});

export declare namespace SearchModelsResponseOthers {
    export interface Raw {
        data?: SearchModelsResponseOthersData.Raw | null;
    }
}
