// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Model } from "../../../types/Model.js";

export const SetDefaultModelResponseOthers: core.serialization.ObjectSchema<
    serializers.SetDefaultModelResponseOthers.Raw,
    FlaqzApp.SetDefaultModelResponseOthers
> = core.serialization.object({
    data: Model.optional(),
});

export declare namespace SetDefaultModelResponseOthers {
    export interface Raw {
        data?: Model.Raw | null;
    }
}
