// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SetDefaultModelResponseOthers } from "./SetDefaultModelResponseOthers.js";

export const SetDefaultModelResponse: core.serialization.ObjectSchema<
    serializers.SetDefaultModelResponse.Raw,
    FlaqzApp.SetDefaultModelResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: SetDefaultModelResponseOthers,
});

export declare namespace SetDefaultModelResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: SetDefaultModelResponseOthers.Raw;
    }
}
