// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { UpdateModelResponseOthers } from "./UpdateModelResponseOthers.js";

export const UpdateModelResponse: core.serialization.ObjectSchema<
    serializers.UpdateModelResponse.Raw,
    FlaqzApp.UpdateModelResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: UpdateModelResponseOthers,
});

export declare namespace UpdateModelResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: UpdateModelResponseOthers.Raw;
    }
}
