// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { CreateManyCustomersResponseOthers } from "./CreateManyCustomersResponseOthers.js";

export const CreateManyCustomersResponse: core.serialization.ObjectSchema<
    serializers.CreateManyCustomersResponse.Raw,
    FlaqzApp.CreateManyCustomersResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: CreateManyCustomersResponseOthers,
});

export declare namespace CreateManyCustomersResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: CreateManyCustomersResponseOthers.Raw;
    }
}
