// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Customer } from "../../../types/Customer.js";

export const CreateCustomerResponseOthers: core.serialization.ObjectSchema<
    serializers.CreateCustomerResponseOthers.Raw,
    FlaqzApp.CreateCustomerResponseOthers
> = core.serialization.object({
    data: Customer.optional(),
});

export declare namespace CreateCustomerResponseOthers {
    export interface Raw {
        data?: Customer.Raw | null;
    }
}
