// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const CreateManyCustomersResponseOthers: core.serialization.ObjectSchema<
    serializers.CreateManyCustomersResponseOthers.Raw,
    FlaqzApp.CreateManyCustomersResponseOthers
> = core.serialization.object({
    data: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace CreateManyCustomersResponseOthers {
    export interface Raw {
        data?: string[] | null;
    }
}
