// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { CreateCustomerResponseOthers } from "./CreateCustomerResponseOthers.js";

export const CreateCustomerResponse: core.serialization.ObjectSchema<
    serializers.CreateCustomerResponse.Raw,
    FlaqzApp.CreateCustomerResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: CreateCustomerResponseOthers,
});

export declare namespace CreateCustomerResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: CreateCustomerResponseOthers.Raw;
    }
}
