// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetAllCustomersResponseOthersData } from "./GetAllCustomersResponseOthersData.js";

export const GetAllCustomersResponseOthers: core.serialization.ObjectSchema<
    serializers.GetAllCustomersResponseOthers.Raw,
    FlaqzApp.GetAllCustomersResponseOthers
> = core.serialization.object({
    data: GetAllCustomersResponseOthersData.optional(),
});

export declare namespace GetAllCustomersResponseOthers {
    export interface Raw {
        data?: GetAllCustomersResponseOthersData.Raw | null;
    }
}
