// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Customer } from "../../../types/Customer.js";

export const GetAllCustomersResponseOthersData: core.serialization.ObjectSchema<
    serializers.GetAllCustomersResponseOthersData.Raw,
    FlaqzApp.GetAllCustomersResponseOthersData
> = core.serialization.object({
    data: core.serialization.list(Customer),
    total: core.serialization.string(),
});

export declare namespace GetAllCustomersResponseOthersData {
    export interface Raw {
        data: Customer.Raw[];
        total: string;
    }
}
