// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetAllCustomersResponseOthers } from "./GetAllCustomersResponseOthers.js";

export const GetAllCustomersResponse: core.serialization.ObjectSchema<
    serializers.GetAllCustomersResponse.Raw,
    FlaqzApp.GetAllCustomersResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: GetAllCustomersResponseOthers,
});

export declare namespace GetAllCustomersResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: GetAllCustomersResponseOthers.Raw;
    }
}
