// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SearchCustomersResponseOthers } from "./SearchCustomersResponseOthers.js";

export const SearchCustomersResponse: core.serialization.ObjectSchema<
    serializers.SearchCustomersResponse.Raw,
    FlaqzApp.SearchCustomersResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: SearchCustomersResponseOthers,
});

export declare namespace SearchCustomersResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: SearchCustomersResponseOthers.Raw;
    }
}
