// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Customer } from "../../../types/Customer.js";

export const SearchCustomersResponseOthersData: core.serialization.ObjectSchema<
    serializers.SearchCustomersResponseOthersData.Raw,
    FlaqzApp.SearchCustomersResponseOthersData
> = core.serialization.object({
    data: core.serialization.list(Customer),
    total: core.serialization.number(),
});

export declare namespace SearchCustomersResponseOthersData {
    export interface Raw {
        data: Customer.Raw[];
        total: number;
    }
}
