// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SearchCustomersResponseOthersData } from "./SearchCustomersResponseOthersData.js";

export const SearchCustomersResponseOthers: core.serialization.ObjectSchema<
    serializers.SearchCustomersResponseOthers.Raw,
    FlaqzApp.SearchCustomersResponseOthers
> = core.serialization.object({
    data: SearchCustomersResponseOthersData.optional(),
});

export declare namespace SearchCustomersResponseOthers {
    export interface Raw {
        data?: SearchCustomersResponseOthersData.Raw | null;
    }
}
