// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const LoginInput: core.serialization.Schema<serializers.LoginInput.Raw, FlaqzApp.LoginInput> =
    core.serialization.object({
        email: core.serialization.string(),
        pass: core.serialization.string(),
    });

export declare namespace LoginInput {
    export interface Raw {
        email: string;
        pass: string;
    }
}
