// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const LogoutInput: core.serialization.Schema<serializers.LogoutInput.Raw, FlaqzApp.LogoutInput> =
    core.serialization.object({
        sessionId: core.serialization.string().optional(),
        isGlobal: core.serialization.boolean().optional(),
    });

export declare namespace LogoutInput {
    export interface Raw {
        sessionId?: string | null;
        isGlobal?: boolean | null;
    }
}
