// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const RefreshInput: core.serialization.Schema<serializers.RefreshInput.Raw, FlaqzApp.RefreshInput> =
    core.serialization.object({
        refreshToken: core.serialization.string(),
    });

export declare namespace RefreshInput {
    export interface Raw {
        refreshToken: string;
    }
}
