// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { SearchAssistantsResponseOthersData } from "./SearchAssistantsResponseOthersData.js";

export const SearchAssistantsResponseOthers: core.serialization.ObjectSchema<
    serializers.SearchAssistantsResponseOthers.Raw,
    FlaqzApp.SearchAssistantsResponseOthers
> = core.serialization.object({
    data: SearchAssistantsResponseOthersData.optional(),
});

export declare namespace SearchAssistantsResponseOthers {
    export interface Raw {
        data?: SearchAssistantsResponseOthersData.Raw | null;
    }
}
