// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Assistant } from "../../../types/Assistant.js";

export const SearchAssistantsResponseOthersData: core.serialization.ObjectSchema<
    serializers.SearchAssistantsResponseOthersData.Raw,
    FlaqzApp.SearchAssistantsResponseOthersData
> = core.serialization.object({
    data: core.serialization.list(Assistant),
    total: core.serialization.number(),
});

export declare namespace SearchAssistantsResponseOthersData {
    export interface Raw {
        data: Assistant.Raw[];
        total: number;
    }
}
