// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AssistantBgSound: core.serialization.Schema<serializers.AssistantBgSound.Raw, FlaqzApp.AssistantBgSound> =
    core.serialization.enum_(["OFF", "OFFICE", "DEFAULT"]);

export declare namespace AssistantBgSound {
    export type Raw = "OFF" | "OFFICE" | "DEFAULT";
}
