// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AssistantStructuredOutputIdsItem: core.serialization.Schema<
    serializers.AssistantStructuredOutputIdsItem.Raw,
    FlaqzApp.AssistantStructuredOutputIdsItem
> = core.serialization.enum_([
    "SALE_COMPLETED",
    "LEAD_STATUS",
    "SUCCESS_EVAL_STRING",
    "SUCCESS_EVAL_NUM",
    "PRODUCT_INTEREST_LEVEL",
    "UPSELL_IDENTIFIED",
    "CALL_SUMMARY",
]);

export declare namespace AssistantStructuredOutputIdsItem {
    export type Raw =
        | "SALE_COMPLETED"
        | "LEAD_STATUS"
        | "SUCCESS_EVAL_STRING"
        | "SUCCESS_EVAL_NUM"
        | "PRODUCT_INTEREST_LEVEL"
        | "UPSELL_IDENTIFIED"
        | "CALL_SUMMARY";
}
