// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AssistantFirstMsgMode: core.serialization.Schema<
    serializers.AssistantFirstMsgMode.Raw,
    FlaqzApp.AssistantFirstMsgMode
> = core.serialization.enum_(["SPEAKS_FIRST_WITH_MSG", "SPEAKS_FIRST", "WAIT_FOR_USER"]);

export declare namespace AssistantFirstMsgMode {
    export type Raw = "SPEAKS_FIRST_WITH_MSG" | "SPEAKS_FIRST" | "WAIT_FOR_USER";
}
