// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AssistantBgSound } from "./AssistantBgSound.js";
import { AssistantFirstMsgMode } from "./AssistantFirstMsgMode.js";
import { AssistantStructuredOutputIdsItem } from "./AssistantStructuredOutputIdsItem.js";
import { Model } from "./Model.js";
import { Transcriber } from "./Transcriber.js";
import { Voice } from "./Voice.js";

export const Assistant: core.serialization.ObjectSchema<serializers.Assistant.Raw, FlaqzApp.Assistant> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        slug: core.serialization.string(),
        voiceId: core.serialization.string(),
        voice: Voice,
        modelId: core.serialization.string(),
        model: Model,
        transcriberId: core.serialization.string(),
        transcriber: Transcriber,
        prompt: core.serialization.string(),
        firstMsg: core.serialization.string(),
        firstMsgMode: AssistantFirstMsgMode,
        voiceMailMsg: core.serialization.string(),
        endMsg: core.serialization.string(),
        bgSound: AssistantBgSound,
        bgDenoising: core.serialization.boolean(),
        structuredOutputIds: core.serialization.list(AssistantStructuredOutputIdsItem),
        createdAt: core.serialization.date(),
    });

export declare namespace Assistant {
    export interface Raw {
        id: string;
        name: string;
        slug: string;
        voiceId: string;
        voice: Voice.Raw;
        modelId: string;
        model: Model.Raw;
        transcriberId: string;
        transcriber: Transcriber.Raw;
        prompt: string;
        firstMsg: string;
        firstMsgMode: AssistantFirstMsgMode.Raw;
        voiceMailMsg: string;
        endMsg: string;
        bgSound: AssistantBgSound.Raw;
        bgDenoising: boolean;
        structuredOutputIds: AssistantStructuredOutputIdsItem.Raw[];
        createdAt: string;
    }
}
