// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AuthTokens: core.serialization.ObjectSchema<serializers.AuthTokens.Raw, FlaqzApp.AuthTokens> =
    core.serialization.object({
        accessToken: core.serialization.string(),
        refreshToken: core.serialization.string(),
        expiresIn: core.serialization.number(),
    });

export declare namespace AuthTokens {
    export interface Raw {
        accessToken: string;
        refreshToken: string;
        expiresIn: number;
    }
}
