// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Customer } from "./Customer.js";

export const Campaign: core.serialization.ObjectSchema<serializers.Campaign.Raw, FlaqzApp.Campaign> =
    core.serialization.object({
        id: core.serialization.string(),
        assistantId: core.serialization.string(),
        customers: core.serialization.list(Customer),
        published: core.serialization.boolean(),
        createdAt: core.serialization.date(),
    });

export declare namespace Campaign {
    export interface Raw {
        id: string;
        assistantId: string;
        customers: Customer.Raw[];
        published: boolean;
        createdAt: string;
    }
}
