// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CreateCampaignInput: core.serialization.ObjectSchema<
    serializers.CreateCampaignInput.Raw,
    FlaqzApp.CreateCampaignInput
> = core.serialization.object({
    campaignName: core.serialization.string(),
    assistantId: core.serialization.string(),
    customerIds: core.serialization.list(core.serialization.string()),
    published: core.serialization.boolean(),
});

export declare namespace CreateCampaignInput {
    export interface Raw {
        campaignName: string;
        assistantId: string;
        customerIds: string[];
        published: boolean;
    }
}
