// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CreateCustomerInput: core.serialization.ObjectSchema<
    serializers.CreateCustomerInput.Raw,
    FlaqzApp.CreateCustomerInput
> = core.serialization.object({
    email: core.serialization.string(),
    firstName: core.serialization.string(),
    lastName: core.serialization.string(),
    phoneNumber: core.serialization.string(),
    obs: core.serialization.string().nullable(),
    cpf: core.serialization.string(),
    birthDate: core.serialization.string().nullable(),
    ppInfo: core.serialization.string().nullable(),
});

export declare namespace CreateCustomerInput {
    export interface Raw {
        email: string;
        firstName: string;
        lastName: string;
        phoneNumber: string;
        obs?: string | null;
        cpf: string;
        birthDate?: string | null;
        ppInfo?: string | null;
    }
}
