// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Customer } from "./Customer.js";

export const CreateCampaignInput: core.serialization.ObjectSchema<
    serializers.CreateCampaignInput.Raw,
    FlaqzApp.CreateCampaignInput
> = core.serialization.object({
    campaignName: core.serialization.string(),
    assistantId: core.serialization.string(),
    customers: core.serialization.list(Customer),
    published: core.serialization.boolean(),
});

export declare namespace CreateCampaignInput {
    export interface Raw {
        campaignName: string;
        assistantId: string;
        customers: Customer.Raw[];
        published: boolean;
    }
}
