// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CreateCustomerInput: core.serialization.ObjectSchema<
    serializers.CreateCustomerInput.Raw,
    FlaqzApp.CreateCustomerInput
> = core.serialization.object({
    email: core.serialization.string(),
    fullName: core.serialization.string().optionalNullable(),
    phoneNumber: core.serialization.string(),
    ppInfo: core.serialization.string().nullable(),
});

export declare namespace CreateCustomerInput {
    export interface Raw {
        email: string;
        fullName?: (string | null | undefined) | null;
        phoneNumber: string;
        ppInfo?: string | null;
    }
}
