// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CreateAssistantInputBgSound: core.serialization.Schema<
    serializers.CreateAssistantInputBgSound.Raw,
    FlaqzApp.CreateAssistantInputBgSound
> = core.serialization.enum_(["OFF", "OFFICE", "DEFAULT"]);

export declare namespace CreateAssistantInputBgSound {
    export type Raw = "OFF" | "OFFICE" | "DEFAULT";
}
