// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CreateModelInput: core.serialization.ObjectSchema<
    serializers.CreateModelInput.Raw,
    FlaqzApp.CreateModelInput
> = core.serialization.object({
    model: core.serialization.string().nullable(),
    provider: core.serialization.string().nullable(),
    maxTokens: core.serialization.string().nullable(),
    temperature: core.serialization.number().nullable(),
});

export declare namespace CreateModelInput {
    export interface Raw {
        model?: string | null;
        provider?: string | null;
        maxTokens?: string | null;
        temperature?: number | null;
    }
}
