// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CreateAssistantInputBgSound } from "./CreateAssistantInputBgSound.js";
import { CreateAssistantInputFirstMsgMode } from "./CreateAssistantInputFirstMsgMode.js";
import { CreateAssistantInputStructuredOutputIdsItem } from "./CreateAssistantInputStructuredOutputIdsItem.js";

export const CreateAssistantInput: core.serialization.ObjectSchema<
    serializers.CreateAssistantInput.Raw,
    FlaqzApp.CreateAssistantInput
> = core.serialization.object({
    name: core.serialization.string(),
    voiceId: core.serialization.string(),
    modelId: core.serialization.string(),
    transcriberId: core.serialization.string(),
    prompt: core.serialization.string(),
    firstMsg: core.serialization.string(),
    firstMsgMode: CreateAssistantInputFirstMsgMode,
    voiceMailMsg: core.serialization.string(),
    endMsg: core.serialization.string(),
    bgSound: CreateAssistantInputBgSound,
    bgDenoising: core.serialization.boolean(),
    structuredOutputIds: core.serialization.list(CreateAssistantInputStructuredOutputIdsItem),
});

export declare namespace CreateAssistantInput {
    export interface Raw {
        name: string;
        voiceId: string;
        modelId: string;
        transcriberId: string;
        prompt: string;
        firstMsg: string;
        firstMsgMode: CreateAssistantInputFirstMsgMode.Raw;
        voiceMailMsg: string;
        endMsg: string;
        bgSound: CreateAssistantInputBgSound.Raw;
        bgDenoising: boolean;
        structuredOutputIds: CreateAssistantInputStructuredOutputIdsItem.Raw[];
    }
}
