// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DeleteCampaign: core.serialization.ObjectSchema<serializers.DeleteCampaign.Raw, FlaqzApp.DeleteCampaign> =
    core.serialization.object({
        id: core.serialization.string(),
    });

export declare namespace DeleteCampaign {
    export interface Raw {
        id: string;
    }
}
