// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Model: core.serialization.ObjectSchema<serializers.Model.Raw, FlaqzApp.Model> = core.serialization.object({
    id: core.serialization.string(),
    model: core.serialization.string(),
    provider: core.serialization.string(),
    maxTokens: core.serialization.string(),
    temperature: core.serialization.number(),
    createdAt: core.serialization.date(),
});

export declare namespace Model {
    export interface Raw {
        id: string;
        model: string;
        provider: string;
        maxTokens: string;
        temperature: number;
        createdAt: string;
    }
}
