// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SearchTranscriber: core.serialization.ObjectSchema<
    serializers.SearchTranscriber.Raw,
    FlaqzApp.SearchTranscriber
> = core.serialization.object({
    page: core.serialization.number(),
    pageSize: core.serialization.number(),
    query: core.serialization.string(),
});

export declare namespace SearchTranscriber {
    export interface Raw {
        page: number;
        pageSize: number;
        query: string;
    }
}
