// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SearchCustomer: core.serialization.ObjectSchema<serializers.SearchCustomer.Raw, FlaqzApp.SearchCustomer> =
    core.serialization.object({
        page: core.serialization.number(),
        pageSize: core.serialization.number(),
        query: core.serialization.string(),
    });

export declare namespace SearchCustomer {
    export interface Raw {
        page: number;
        pageSize: number;
        query: string;
    }
}
