// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Transcriber: core.serialization.ObjectSchema<serializers.Transcriber.Raw, FlaqzApp.Transcriber> =
    core.serialization.object({
        id: core.serialization.string(),
        model: core.serialization.string(),
        language: core.serialization.string(),
        provider: core.serialization.string(),
        createdAt: core.serialization.date(),
    });

export declare namespace Transcriber {
    export interface Raw {
        id: string;
        model: string;
        language: string;
        provider: string;
        createdAt: string;
    }
}
