// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CreateCampaignInput } from "./CreateCampaignInput.js";

export const UpdateCampaign: core.serialization.ObjectSchema<serializers.UpdateCampaign.Raw, FlaqzApp.UpdateCampaign> =
    core.serialization.object({
        newData: CreateCampaignInput,
    });

export declare namespace UpdateCampaign {
    export interface Raw {
        newData: CreateCampaignInput.Raw;
    }
}
