// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const User: core.serialization.ObjectSchema<serializers.User.Raw, FlaqzApp.User> = core.serialization.object({
    id: core.serialization.string(),
    email: core.serialization.string(),
    username: core.serialization.string(),
    createdAt: core.serialization.date(),
});

export declare namespace User {
    export interface Raw {
        id: string;
        email: string;
        username: string;
        createdAt: string;
    }
}
