// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const UserRole: core.serialization.Schema<serializers.UserRole.Raw, FlaqzApp.UserRole> =
    core.serialization.enum_(["ADMIN", "MANAGER", "USER"]);

export declare namespace UserRole {
    export type Raw = "ADMIN" | "MANAGER" | "USER";
}
