// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Voice: core.serialization.ObjectSchema<serializers.Voice.Raw, FlaqzApp.Voice> = core.serialization.object({
    id: core.serialization.string(),
    provider: core.serialization.string(),
    model: core.serialization.string(),
    voiceId: core.serialization.string(),
    autoMode: core.serialization.boolean(),
    speed: core.serialization.number(),
    style: core.serialization.number(),
    stability: core.serialization.number(),
    similarity: core.serialization.number(),
    optimize: core.serialization.number(),
    createdAt: core.serialization.date(),
});

export declare namespace Voice {
    export interface Raw {
        id: string;
        provider: string;
        model: string;
        voiceId: string;
        autoMode: boolean;
        speed: number;
        style: number;
        stability: number;
        similarity: number;
        optimize: number;
        createdAt: string;
    }
}
