// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { CreateCampaignInput } from "../../../../types/CreateCampaignInput.js";

export const UpdateCampaignRequest: core.serialization.Schema<
    serializers.UpdateCampaignRequest.Raw,
    Omit<FlaqzApp.UpdateCampaignRequest, "id">
> = core.serialization.object({
    newData: CreateCampaignInput,
});

export declare namespace UpdateCampaignRequest {
    export interface Raw {
        newData: CreateCampaignInput.Raw;
    }
}
