// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../index.js";

export interface CreateVoiceResponse {
    status: number;
    success: boolean;
    message: string;
    others: FlaqzApp.CreateVoiceResponseOthers;
}
