// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../index.js";

export interface SearchVoicesResponseOthers {
    data?: FlaqzApp.SearchVoicesResponseOthersData;
}
