// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         model: "llama-3.1-8b-instant",
 *         provider: "groq",
 *         maxTokens: 128,
 *         temperature: 0.6
 *     }
 */
export interface CreateModelInput {
    model: string | null;
    provider: string | null;
    maxTokens: number | null;
    temperature: number | null;
}
