// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         model: "nova-2",
 *         provider: "deepgram"
 *     }
 */
export interface CreateModelInput {
    model: string | null;
    provider: string | null;
    maxTokens: number | null;
    temperature: number | null;
}
