// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             model: "llama-3.1-8b-instant",
 *             provider: "groq",
 *             maxTokens: 128,
 *             temperature: 0.6
 *         }
 *     }
 */
export interface UpdateModelRequest {
    id: string;
    body: FlaqzApp.CreateModelInput;
}
