// This file was auto-generated by Fern from our API Definition.

export interface CreateManyCustomersResponse {
    status: number;
    success: boolean;
    message: string;
    others: CreateManyCustomersResponse.Others;
}

export namespace CreateManyCustomersResponse {
    export interface Others {
        data?: string[];
    }
}
