// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../index.js";

export interface GetAllCustomersResponseOthersData {
    data: FlaqzApp.Customer[];
    total: number;
}
