// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../index.js";

export interface GetAllCustomersResponse {
    status: number;
    success: boolean;
    message: string;
    others: GetAllCustomersResponse.Others;
}

export namespace GetAllCustomersResponse {
    export interface Others {
        data?: FlaqzApp.Customer[];
    }
}
