// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateVoiceInput: core.serialization.Schema<serializers.CreateVoiceInput.Raw, FlaqzApp.CreateVoiceInput> =
    core.serialization.object({
        provider: core.serialization.string().nullable(),
        model: core.serialization.string().nullable(),
        voiceId: core.serialization.string().nullable(),
        autoMode: core.serialization.boolean().nullable(),
        speed: core.serialization.number().nullable(),
        style: core.serialization.number().nullable(),
        stability: core.serialization.number().nullable(),
        similarity: core.serialization.number().nullable(),
        optimize: core.serialization.number().nullable(),
    });

export declare namespace CreateVoiceInput {
    export interface Raw {
        provider?: string | null;
        model?: string | null;
        voiceId?: string | null;
        autoMode?: boolean | null;
        speed?: number | null;
        style?: number | null;
        stability?: number | null;
        similarity?: number | null;
        optimize?: number | null;
    }
}
