// This file was auto-generated by Fern from our API Definition.

import * as FlaqzApp from "../../src/api/index";
import { FlaqzAppClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AuthClient", () => {
    test("login", async () => {
        const server = mockServerPool.createServer();
        const client = new FlaqzAppClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { email: "user@example.com", pass: "securepassword" };
        const rawResponseBody = {
            status: 1,
            success: true,
            message: "message",
            others: { data: { accessToken: "accessToken", refreshToken: "refreshToken", expiresIn: 1.1 } },
        };
        server
            .mockEndpoint()
            .post("/api/v1/auth/login")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.auth.login({
            email: "user@example.com",
            pass: "securepassword",
        });
        expect(response).toEqual({
            status: 1,
            success: true,
            message: "message",
            others: {
                data: {
                    accessToken: "accessToken",
                    refreshToken: "refreshToken",
                    expiresIn: 1.1,
                },
            },
        });
    });

    test("refresh", async () => {
        const server = mockServerPool.createServer();
        const client = new FlaqzAppClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { refreshToken: "refreshToken" };
        const rawResponseBody = {
            status: 1,
            success: true,
            message: "message",
            others: { data: { accessToken: "accessToken", refreshToken: "refreshToken", expiresIn: 1.1 } },
        };
        server
            .mockEndpoint()
            .post("/api/v1/auth/refresh")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.auth.refresh({
            refreshToken: "refreshToken",
        });
        expect(response).toEqual({
            status: 1,
            success: true,
            message: "message",
            others: {
                data: {
                    accessToken: "accessToken",
                    refreshToken: "refreshToken",
                    expiresIn: 1.1,
                },
            },
        });
    });

    test("logout (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new FlaqzAppClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { isGlobal: false };

        server
            .mockEndpoint()
            .post("/api/v1/auth/logout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.auth.logout({
            isGlobal: false,
        });
        expect(response).toEqual(undefined);
    });

    test("logout (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new FlaqzAppClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/api/v1/auth/logout")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.auth.logout();
        }).rejects.toThrow(FlaqzApp.ForbiddenError);
    });
});
