// This file was auto-generated by Fern from our API Definition.

import { FlaqzAppClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CampaignsClient", () => {
    test("getCampaigns", async () => {
        const server = mockServerPool.createServer();
        const client = new FlaqzAppClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            success: true,
            message: "message",
            others: {
                data: [
                    {
                        id: "6f727d0e-a169-4e24-8b5e-637077d57f35",
                        campaignName: "My Awesome Campaign",
                        assistantId: "8df037de-a169-4e24-8b5e-637077d57f35",
                        customers: [
                            {
                                id: "8f727d7e-a169-4e24-8b5e-637077d57f35",
                                email: "awesome@customer.com",
                                fullName: "Awesome Customer",
                                phoneNumber: "+10000000000",
                                ppInfo: "Under financial history analysis",
                                createdAt: "2000-01-01T00:00:00Z",
                            },
                            {
                                id: "df727d0e-a169-4e27-8b5e-637077d57f35",
                                email: "boring@customer.com",
                                fullName: "Boring Customer",
                                phoneNumber: "+10000000000",
                                ppInfo: "Under financial history analysis",
                                createdAt: "2000-01-01T00:00:00Z",
                            },
                        ],
                        published: true,
                        createdAt: "2000-01-01T00:00:00Z",
                    },
                ],
            },
        };
        server.mockEndpoint().get("/api/v1/campaigns").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.campaigns.getCampaigns();
        expect(response).toEqual({
            status: 1,
            success: true,
            message: "message",
            others: {
                data: [
                    {
                        id: "6f727d0e-a169-4e24-8b5e-637077d57f35",
                        campaignName: "My Awesome Campaign",
                        assistantId: "8df037de-a169-4e24-8b5e-637077d57f35",
                        customers: [
                            {
                                id: "8f727d7e-a169-4e24-8b5e-637077d57f35",
                                email: "awesome@customer.com",
                                fullName: "Awesome Customer",
                                phoneNumber: "+10000000000",
                                ppInfo: "Under financial history analysis",
                                createdAt: new Date("2000-01-01T00:00:00.000Z"),
                            },
                            {
                                id: "df727d0e-a169-4e27-8b5e-637077d57f35",
                                email: "boring@customer.com",
                                fullName: "Boring Customer",
                                phoneNumber: "+10000000000",
                                ppInfo: "Under financial history analysis",
                                createdAt: new Date("2000-01-01T00:00:00.000Z"),
                            },
                        ],
                        published: true,
                        createdAt: new Date("2000-01-01T00:00:00.000Z"),
                    },
                ],
            },
        });
    });

    test("runCampaign", async () => {
        const server = mockServerPool.createServer();
        const client = new FlaqzAppClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { status: 1, success: true, message: "message", others: {} };
        server
            .mockEndpoint()
            .post("/api/v1/campaigns/df727d0e-a169-4e24-8b5e-637077d57f35/run")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.campaigns.runCampaign({
            id: "df727d0e-a169-4e24-8b5e-637077d57f35",
        });
        expect(response).toEqual({
            status: 1,
            success: true,
            message: "message",
            others: {},
        });
    });
});
