// This file was auto-generated by Fern from our API Definition.

import { FlaqzAppClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CustomerClient", () => {
    test("getAllCustomers", async () => {
        const server = mockServerPool.createServer();
        const client = new FlaqzAppClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            success: true,
            message: "message",
            others: {
                data: [
                    {
                        id: "6f727d0e-a169-4e24-8b5e-637077d57f35",
                        email: "awesome@customer.com",
                        firstName: "Awesome",
                        lastName: "Customer",
                        phoneNumber: "+10000000000",
                        obs: "Mr. Awesome like oranges",
                        cpf: "00000000000",
                        birthDate: "2000-01-01",
                        ppInfo: "Under financial history analisys",
                        createdAt: "2000-01-01T00:00:00Z",
                    },
                ],
            },
        };
        server.mockEndpoint().get("/api/v1/customers").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.customer.getAllCustomers();
        expect(response).toEqual({
            status: 1,
            success: true,
            message: "message",
            others: {
                data: [
                    {
                        id: "6f727d0e-a169-4e24-8b5e-637077d57f35",
                        email: "awesome@customer.com",
                        firstName: "Awesome",
                        lastName: "Customer",
                        phoneNumber: "+10000000000",
                        obs: "Mr. Awesome like oranges",
                        cpf: "00000000000",
                        birthDate: "2000-01-01",
                        ppInfo: "Under financial history analisys",
                        createdAt: new Date("2000-01-01T00:00:00.000Z"),
                    },
                ],
            },
        });
    });

    test("createManyCustomers", async () => {
        const server = mockServerPool.createServer();
        const client = new FlaqzAppClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {
            customers: [
                {
                    email: "awesome@customer.com",
                    firstName: "Awesome",
                    lastName: "Customer",
                    phoneNumber: "+10000000000",
                    obs: "Mr. Awesome like oranges",
                    cpf: "00000000000",
                    birthDate: "2000-01-01",
                    ppInfo: "Under financial history analisys",
                },
            ],
        };
        const rawResponseBody = { status: 1, success: true, message: "message", others: { data: ["data"] } };
        server
            .mockEndpoint()
            .post("/api/v1/many-customers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.customer.createManyCustomers({
            customers: [
                {
                    email: "awesome@customer.com",
                    firstName: "Awesome",
                    lastName: "Customer",
                    phoneNumber: "+10000000000",
                    obs: "Mr. Awesome like oranges",
                    cpf: "00000000000",
                    birthDate: "2000-01-01",
                    ppInfo: "Under financial history analisys",
                },
            ],
        });
        expect(response).toEqual({
            status: 1,
            success: true,
            message: "message",
            others: {
                data: ["data"],
            },
        });
    });
});
