// This file was auto-generated by Fern from our API Definition.

import { FlaqzAppClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TranscriberClient", () => {
    test("gettranscribers", async () => {
        const server = mockServerPool.createServer();
        const client = new FlaqzAppClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            success: true,
            message: "message",
            others: {
                data: {
                    data: [
                        {
                            id: "6f727d0e-a169-4e24-8b5e-637077d57f35",
                            model: "nova-2",
                            language: "pt-BR",
                            provider: "deepgram",
                            createdAt: "2000-01-01T00:00:00Z",
                        },
                    ],
                    total: 1,
                },
            },
        };
        server
            .mockEndpoint()
            .get("/api/v1/transcribers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transcriber.gettranscribers({
            page: 1,
            pageSize: 20,
        });
        expect(response).toEqual({
            status: 1,
            success: true,
            message: "message",
            others: {
                data: {
                    data: [
                        {
                            id: "6f727d0e-a169-4e24-8b5e-637077d57f35",
                            model: "nova-2",
                            language: "pt-BR",
                            provider: "deepgram",
                            createdAt: new Date("2000-01-01T00:00:00.000Z"),
                        },
                    ],
                    total: 1,
                },
            },
        });
    });

    test("createTranscriber", async () => {
        const server = mockServerPool.createServer();
        const client = new FlaqzAppClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { model: "nova-2", language: "pt-BR", provider: "deepgram" };
        const rawResponseBody = {
            status: 1,
            success: true,
            message: "message",
            others: {
                data: {
                    id: "6f727d0e-a169-4e24-8b5e-637077d57f35",
                    model: "nova-2",
                    language: "pt-BR",
                    provider: "deepgram",
                    createdAt: "2000-01-01T00:00:00Z",
                },
            },
        };
        server
            .mockEndpoint()
            .post("/api/v1/transcribers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transcriber.createTranscriber({
            model: "nova-2",
            language: "pt-BR",
            provider: "deepgram",
        });
        expect(response).toEqual({
            status: 1,
            success: true,
            message: "message",
            others: {
                data: {
                    id: "6f727d0e-a169-4e24-8b5e-637077d57f35",
                    model: "nova-2",
                    language: "pt-BR",
                    provider: "deepgram",
                    createdAt: new Date("2000-01-01T00:00:00.000Z"),
                },
            },
        });
    });

    test("searchTranscribers", async () => {
        const server = mockServerPool.createServer();
        const client = new FlaqzAppClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            success: true,
            message: "message",
            others: {
                data: {
                    data: [
                        {
                            id: "6f727d0e-a169-4e24-8b5e-637077d57f35",
                            model: "nova-2",
                            language: "pt-BR",
                            provider: "deepgram",
                            createdAt: "2000-01-01T00:00:00Z",
                        },
                    ],
                    total: 1,
                },
            },
        };
        server
            .mockEndpoint()
            .get("/api/v1/transcribers/search")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transcriber.searchTranscribers({
            page: 1,
            pageSize: 20,
            query: "Awesome Customer",
        });
        expect(response).toEqual({
            status: 1,
            success: true,
            message: "message",
            others: {
                data: {
                    data: [
                        {
                            id: "6f727d0e-a169-4e24-8b5e-637077d57f35",
                            model: "nova-2",
                            language: "pt-BR",
                            provider: "deepgram",
                            createdAt: new Date("2000-01-01T00:00:00.000Z"),
                        },
                    ],
                    total: 1,
                },
            },
        });
    });
});
