// This file was auto-generated by Fern from our API Definition.

import { FlaqzAppClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("UserClient", () => {
    test("getUsers", async () => {
        const server = mockServerPool.createServer();
        const client = new FlaqzAppClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            success: true,
            message: "message",
            others: {
                data: [
                    {
                        id: "6f727d0e-a169-4e24-8b5e-637077d57f35",
                        email: "user@example.com",
                        username: "johndoe",
                        createdAt: "2000-01-01T00:00:00Z",
                    },
                ],
            },
        };
        server.mockEndpoint().get("/api/v1/users").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.user.getUsers();
        expect(response).toEqual({
            status: 1,
            success: true,
            message: "message",
            others: {
                data: [
                    {
                        id: "6f727d0e-a169-4e24-8b5e-637077d57f35",
                        email: "user@example.com",
                        username: "johndoe",
                        createdAt: new Date("2000-01-01T00:00:00.000Z"),
                    },
                ],
            },
        });
    });

    test("createUser", async () => {
        const server = mockServerPool.createServer();
        const client = new FlaqzAppClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { email: "user@example.com", username: "johndoe", pass: "securepassword" };
        const rawResponseBody = {
            status: 1,
            success: true,
            message: "message",
            others: {
                data: {
                    id: "6f727d0e-a169-4e24-8b5e-637077d57f35",
                    email: "user@example.com",
                    username: "johndoe",
                    createdAt: "2000-01-01T00:00:00Z",
                },
            },
        };
        server
            .mockEndpoint()
            .post("/api/v1/users")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.user.createUser({
            email: "user@example.com",
            username: "johndoe",
            pass: "securepassword",
        });
        expect(response).toEqual({
            status: 1,
            success: true,
            message: "message",
            others: {
                data: {
                    id: "6f727d0e-a169-4e24-8b5e-637077d57f35",
                    email: "user@example.com",
                    username: "johndoe",
                    createdAt: new Date("2000-01-01T00:00:00.000Z"),
                },
            },
        });
    });

    test("searchUsers", async () => {
        const server = mockServerPool.createServer();
        const client = new FlaqzAppClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            status: 1,
            success: true,
            message: "message",
            others: {
                data: {
                    data: [
                        {
                            id: "6f727d0e-a169-4e24-8b5e-637077d57f35",
                            email: "user@example.com",
                            username: "johndoe",
                            createdAt: "2000-01-01T00:00:00Z",
                        },
                    ],
                    total: 1,
                },
            },
        };
        server
            .mockEndpoint()
            .get("/api/v1/users/search")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.user.searchUsers({
            page: 1,
            pageSize: 20,
            query: "johndoe",
        });
        expect(response).toEqual({
            status: 1,
            success: true,
            message: "message",
            others: {
                data: {
                    data: [
                        {
                            id: "6f727d0e-a169-4e24-8b5e-637077d57f35",
                            email: "user@example.com",
                            username: "johndoe",
                            createdAt: new Date("2000-01-01T00:00:00.000Z"),
                        },
                    ],
                    total: 1,
                },
            },
        });
    });

    test("deleteUser", async () => {
        const server = mockServerPool.createServer();
        const client = new FlaqzAppClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { status: 1, success: true, message: "message", others: {} };
        server
            .mockEndpoint()
            .delete("/api/v1/users/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.user.deleteUser({
            id: "id",
        });
        expect(response).toEqual({
            status: 1,
            success: true,
            message: "message",
            others: {},
        });
    });
});
