// This file was auto-generated by Fern from our API Definition.

import { AssistantClient } from "./api/resources/assistant/client/Client.js";
import { CustomerClient } from "./api/resources/customer/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { normalizeClientOptions } from "./BaseClient.js";

export declare namespace FlaqzAppClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class FlaqzAppClient {
    protected readonly _options: FlaqzAppClient.Options;
    protected _customer: CustomerClient | undefined;
    protected _assistant: AssistantClient | undefined;

    constructor(options: FlaqzAppClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    public get customer(): CustomerClient {
        return (this._customer ??= new CustomerClient(this._options));
    }

    public get assistant(): AssistantClient {
        return (this._assistant ??= new AssistantClient(this._options));
    }
}
