// This file was auto-generated by Fern from our API Definition.

export const FlaqzAppEnvironment = {
    Default: "http://localhost:3001",
} as const;

export type FlaqzAppEnvironment = typeof FlaqzAppEnvironment.Default;
