// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         newData: {
 *             campaignName: "My Awesome Campaign",
 *             assistantId: "8df037de-a169-4e24-8b5e-637077d57f35",
 *             customers: [{
 *                     id: "8f727d7e-a169-4e24-8b5e-637077d57f35",
 *                     email: "awesome@customer.com",
 *                     fullName: "Awesome Customer",
 *                     phoneNumber: "+10000000000",
 *                     ppInfo: "Under financial history analysis",
 *                     createdAt: new Date("2000-01-01T00:00:00.000Z")
 *                 }, {
 *                     id: "df727d0e-a169-4e27-8b5e-637077d57f35",
 *                     email: "boring@customer.com",
 *                     fullName: "Boring Customer",
 *                     phoneNumber: "+10000000000",
 *                     ppInfo: "Under financial history analysis",
 *                     createdAt: new Date("2000-01-01T00:00:00.000Z")
 *                 }],
 *             published: true
 *         }
 *     }
 */
export interface UpdateCampaignRequest {
    id: string;
    newData: FlaqzApp.CreateCampaignInput;
}
