// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         newData: {
 *             campaignName: "My Awesome Campaign",
 *             assistantId: "8df037de-a169-4e24-8b5e-637077d57f35",
 *             customerIds: ["8f727d7e-a169-4e24-8b5e-637077d57f35", "df727d0e-a169-4e27-8b5e-637077d57f35"],
 *             published: true
 *         }
 *     }
 */
export interface UpdateCampaignRequest {
    id: string;
    newData: FlaqzApp.CreateCampaignInput;
}
