// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GetCampaignsResponseOthers } from "./GetCampaignsResponseOthers.js";

export const GetCampaignsResponse: core.serialization.ObjectSchema<
    serializers.GetCampaignsResponse.Raw,
    FlaqzApp.GetCampaignsResponse
> = core.serialization.object({
    status: core.serialization.number(),
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    others: GetCampaignsResponseOthers,
});

export declare namespace GetCampaignsResponse {
    export interface Raw {
        status: number;
        success: boolean;
        message: string;
        others: GetCampaignsResponseOthers.Raw;
    }
}
