// This file was auto-generated by Fern from our API Definition.

import type * as FlaqzApp from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { RunCampaignResponseOthersData } from "./RunCampaignResponseOthersData.js";

export const RunCampaignResponseOthers: core.serialization.ObjectSchema<
    serializers.RunCampaignResponseOthers.Raw,
    FlaqzApp.RunCampaignResponseOthers
> = core.serialization.object({
    data: RunCampaignResponseOthersData.optional(),
});

export declare namespace RunCampaignResponseOthers {
    export interface Raw {
        data?: RunCampaignResponseOthersData.Raw | null;
    }
}
